<?php



/**
 * This class defines the structure of the 'sf_asset' table.
 *
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Thu Mar  3 18:13:39 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.sfAssetsLibraryPlugin.lib.model.map
 */
class sfAssetTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfAssetsLibraryPlugin.lib.model.map.sfAssetTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sf_asset');
		$this->setPhpName('sfAsset');
		$this->setClassname('sfAsset');
		$this->setPackage('plugins.sfAssetsLibraryPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('FOLDER_ID', 'FolderId', 'INTEGER', 'sf_asset_folder', 'ID', true, null, null);
		$this->addColumn('FILENAME', 'Filename', 'VARCHAR', true, 255, null);
		$this->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null, null);
		$this->addColumn('AUTHOR', 'Author', 'VARCHAR', false, 255, null);
		$this->addColumn('COPYRIGHT', 'Copyright', 'VARCHAR', false, 100, null);
		$this->addColumn('TYPE', 'Type', 'VARCHAR', false, 10, null);
		$this->addColumn('FILESIZE', 'Filesize', 'INTEGER', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfAssetFolder', 'sfAssetFolder', RelationMap::MANY_TO_ONE, array('folder_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('ProdottoRelatedByFotoBase', 'Prodotto', RelationMap::ONE_TO_MANY, array('id' => 'sf_asset_id', ), 'SET NULL', null);
    $this->addRelation('ProdottoRelatedByThumb01', 'Prodotto', RelationMap::ONE_TO_MANY, array('id' => 'sf_asset_id1', ), 'SET NULL', null);
    $this->addRelation('ProdottoRelatedByThumb02', 'Prodotto', RelationMap::ONE_TO_MANY, array('id' => 'sf_asset_id2', ), 'SET NULL', null);
    $this->addRelation('ProdottoRelatedByThumb03', 'Prodotto', RelationMap::ONE_TO_MANY, array('id' => 'sf_asset_id3', ), 'SET NULL', null);
    $this->addRelation('ProdottoRelatedByThumb04', 'Prodotto', RelationMap::ONE_TO_MANY, array('id' => 'sf_asset_id4', ), 'SET NULL', null);
    $this->addRelation('ProdottoRelatedByThumb05', 'Prodotto', RelationMap::ONE_TO_MANY, array('id' => 'sf_asset_id5', ), 'SET NULL', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // sfAssetTableMap
