<?php


/**
 * Base class that represents a query for the 'sf_asset_folder' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Thu Mar  3 18:13:39 2011
 *
 * @method     sfAssetFolderQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     sfAssetFolderQuery orderByTreeLeft($order = Criteria::ASC) Order by the tree_left column
 * @method     sfAssetFolderQuery orderByTreeRight($order = Criteria::ASC) Order by the tree_right column
 * @method     sfAssetFolderQuery orderByName($order = Criteria::ASC) Order by the name column
 * @method     sfAssetFolderQuery orderByRelativePath($order = Criteria::ASC) Order by the relative_path column
 * @method     sfAssetFolderQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method     sfAssetFolderQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 *
 * @method     sfAssetFolderQuery groupById() Group by the id column
 * @method     sfAssetFolderQuery groupByTreeLeft() Group by the tree_left column
 * @method     sfAssetFolderQuery groupByTreeRight() Group by the tree_right column
 * @method     sfAssetFolderQuery groupByName() Group by the name column
 * @method     sfAssetFolderQuery groupByRelativePath() Group by the relative_path column
 * @method     sfAssetFolderQuery groupByCreatedAt() Group by the created_at column
 * @method     sfAssetFolderQuery groupByUpdatedAt() Group by the updated_at column
 *
 * @method     sfAssetFolderQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     sfAssetFolderQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     sfAssetFolderQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     sfAssetFolderQuery leftJoinsfAsset($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfAsset relation
 * @method     sfAssetFolderQuery rightJoinsfAsset($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfAsset relation
 * @method     sfAssetFolderQuery innerJoinsfAsset($relationAlias = null) Adds a INNER JOIN clause to the query using the sfAsset relation
 *
 * @method     sfAssetFolder findOne(PropelPDO $con = null) Return the first sfAssetFolder matching the query
 * @method     sfAssetFolder findOneOrCreate(PropelPDO $con = null) Return the first sfAssetFolder matching the query, or a new sfAssetFolder object populated from the query conditions when no match is found
 *
 * @method     sfAssetFolder findOneById(int $id) Return the first sfAssetFolder filtered by the id column
 * @method     sfAssetFolder findOneByTreeLeft(int $tree_left) Return the first sfAssetFolder filtered by the tree_left column
 * @method     sfAssetFolder findOneByTreeRight(int $tree_right) Return the first sfAssetFolder filtered by the tree_right column
 * @method     sfAssetFolder findOneByName(string $name) Return the first sfAssetFolder filtered by the name column
 * @method     sfAssetFolder findOneByRelativePath(string $relative_path) Return the first sfAssetFolder filtered by the relative_path column
 * @method     sfAssetFolder findOneByCreatedAt(string $created_at) Return the first sfAssetFolder filtered by the created_at column
 * @method     sfAssetFolder findOneByUpdatedAt(string $updated_at) Return the first sfAssetFolder filtered by the updated_at column
 *
 * @method     array findById(int $id) Return sfAssetFolder objects filtered by the id column
 * @method     array findByTreeLeft(int $tree_left) Return sfAssetFolder objects filtered by the tree_left column
 * @method     array findByTreeRight(int $tree_right) Return sfAssetFolder objects filtered by the tree_right column
 * @method     array findByName(string $name) Return sfAssetFolder objects filtered by the name column
 * @method     array findByRelativePath(string $relative_path) Return sfAssetFolder objects filtered by the relative_path column
 * @method     array findByCreatedAt(string $created_at) Return sfAssetFolder objects filtered by the created_at column
 * @method     array findByUpdatedAt(string $updated_at) Return sfAssetFolder objects filtered by the updated_at column
 *
 * @package    propel.generator.plugins.sfAssetsLibraryPlugin.lib.model.om
 */
abstract class BasesfAssetFolderQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BasesfAssetFolderQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'sfAssetFolder', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new sfAssetFolderQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    sfAssetFolderQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof sfAssetFolderQuery) {
			return $criteria;
		}
		$query = new sfAssetFolderQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    sfAssetFolder|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = sfAssetFolderPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(sfAssetFolderPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(sfAssetFolderPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(sfAssetFolderPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the tree_left column
	 * 
	 * @param     int|array $treeLeft The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterByTreeLeft($treeLeft = null, $comparison = null)
	{
		if (is_array($treeLeft)) {
			$useMinMax = false;
			if (isset($treeLeft['min'])) {
				$this->addUsingAlias(sfAssetFolderPeer::TREE_LEFT, $treeLeft['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($treeLeft['max'])) {
				$this->addUsingAlias(sfAssetFolderPeer::TREE_LEFT, $treeLeft['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(sfAssetFolderPeer::TREE_LEFT, $treeLeft, $comparison);
	}

	/**
	 * Filter the query on the tree_right column
	 * 
	 * @param     int|array $treeRight The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterByTreeRight($treeRight = null, $comparison = null)
	{
		if (is_array($treeRight)) {
			$useMinMax = false;
			if (isset($treeRight['min'])) {
				$this->addUsingAlias(sfAssetFolderPeer::TREE_RIGHT, $treeRight['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($treeRight['max'])) {
				$this->addUsingAlias(sfAssetFolderPeer::TREE_RIGHT, $treeRight['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(sfAssetFolderPeer::TREE_RIGHT, $treeRight, $comparison);
	}

	/**
	 * Filter the query on the name column
	 * 
	 * @param     string $name The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterByName($name = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($name)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $name)) {
				$name = str_replace('*', '%', $name);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(sfAssetFolderPeer::NAME, $name, $comparison);
	}

	/**
	 * Filter the query on the relative_path column
	 * 
	 * @param     string $relativePath The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterByRelativePath($relativePath = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($relativePath)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $relativePath)) {
				$relativePath = str_replace('*', '%', $relativePath);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(sfAssetFolderPeer::RELATIVE_PATH, $relativePath, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(sfAssetFolderPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(sfAssetFolderPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(sfAssetFolderPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query on the updated_at column
	 * 
	 * @param     string|array $updatedAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterByUpdatedAt($updatedAt = null, $comparison = null)
	{
		if (is_array($updatedAt)) {
			$useMinMax = false;
			if (isset($updatedAt['min'])) {
				$this->addUsingAlias(sfAssetFolderPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($updatedAt['max'])) {
				$this->addUsingAlias(sfAssetFolderPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(sfAssetFolderPeer::UPDATED_AT, $updatedAt, $comparison);
	}

	/**
	 * Filter the query by a related sfAsset object
	 *
	 * @param     sfAsset $sfAsset  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function filterBysfAsset($sfAsset, $comparison = null)
	{
		if ($sfAsset instanceof sfAsset) {
			return $this
				->addUsingAlias(sfAssetFolderPeer::ID, $sfAsset->getFolderId(), $comparison);
		} elseif ($sfAsset instanceof PropelCollection) {
			return $this
				->usesfAssetQuery()
					->filterByPrimaryKeys($sfAsset->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterBysfAsset() only accepts arguments of type sfAsset or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the sfAsset relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function joinsfAsset($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('sfAsset');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'sfAsset');
		}
		
		return $this;
	}

	/**
	 * Use the sfAsset relation sfAsset object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfAssetQuery A secondary query class using the current class as primary query
	 */
	public function usesfAssetQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinsfAsset($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'sfAsset', 'sfAssetQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     sfAssetFolder $sfAssetFolder Object to remove from the list of results
	 *
	 * @return    sfAssetFolderQuery The current query, for fluid interface
	 */
	public function prune($sfAssetFolder = null)
	{
		if ($sfAssetFolder) {
			$this->addUsingAlias(sfAssetFolderPeer::ID, $sfAssetFolder->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

	// timestampable behavior
	
	/**
	 * Filter by the latest updated
	 *
	 * @param      int $nbDays Maximum age of the latest update in days
	 *
	 * @return     sfAssetFolderQuery The current query, for fluid interface
	 */
	public function recentlyUpdated($nbDays = 7)
	{
		return $this->addUsingAlias(sfAssetFolderPeer::UPDATED_AT, time() - $nbDays * 24 * 60 * 60, Criteria::GREATER_EQUAL);
	}
	
	/**
	 * Filter by the latest created
	 *
	 * @param      int $nbDays Maximum age of in days
	 *
	 * @return     sfAssetFolderQuery The current query, for fluid interface
	 */
	public function recentlyCreated($nbDays = 7)
	{
		return $this->addUsingAlias(sfAssetFolderPeer::CREATED_AT, time() - $nbDays * 24 * 60 * 60, Criteria::GREATER_EQUAL);
	}
	
	/**
	 * Order by update date desc
	 *
	 * @return     sfAssetFolderQuery The current query, for fluid interface
	 */
	public function lastUpdatedFirst()
	{
		return $this->addDescendingOrderByColumn(sfAssetFolderPeer::UPDATED_AT);
	}
	
	/**
	 * Order by update date asc
	 *
	 * @return     sfAssetFolderQuery The current query, for fluid interface
	 */
	public function firstUpdatedFirst()
	{
		return $this->addAscendingOrderByColumn(sfAssetFolderPeer::UPDATED_AT);
	}
	
	/**
	 * Order by create date desc
	 *
	 * @return     sfAssetFolderQuery The current query, for fluid interface
	 */
	public function lastCreatedFirst()
	{
		return $this->addDescendingOrderByColumn(sfAssetFolderPeer::CREATED_AT);
	}
	
	/**
	 * Order by create date asc
	 *
	 * @return     sfAssetFolderQuery The current query, for fluid interface
	 */
	public function firstCreatedFirst()
	{
		return $this->addAscendingOrderByColumn(sfAssetFolderPeer::CREATED_AT);
	}

} // BasesfAssetFolderQuery
