<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sf_asset_folder' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * Thu Mar 18 13:25:47 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfAssetsLibraryPlugin.lib.model
 */
class sfAssetFolderQuery extends BasesfAssetFolderQuery
{

}
