package: plugins.sfAssetsLibraryPlugin.lib.model

classes:

  sfAssetFolder:
    treeMode: NestedSet
    columns:
      id:            ~
      tree_left:     { type: integer, required: true, default: 0, nestedSetLeftKey: true }
      tree_right:    { type: integer, required: true, default: 0, nestedSetRightKey: true }
      name:          { type: varchar, required: true }
      relative_path: { type: varchar }
    uniques:
      uk_relative_path: [relative_path]
    propel_behaviors:
      timestampable: ~

  sfAsset:
    columns:
      id:               ~
      folder_id:        { type: integer, required: true, foreignClass: sfAssetFolder, foreignReference: id, onDelete: cascade, onUpdate: cascade }
      filename:         { type: varchar, required: true }
      description:      { type: longvarchar }
      author:           { type: varchar }
      copyright:        { type: varchar(100) }
      type:             { type: varchar(10) }
      filesize:         { type: integer }
    uniques:
      uk_folder_filename: [folder_id, filename]
    propel_behaviors:
      timestampable: ~
